version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    depends_on:
        - api-1
        - api-2
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
  
  api-1:
    container_name: api-1
    build:  .
    command: node api.js
    ports: 
      - "8081:8080"
    volumes:
      - .:/api

  api-2:
    container_name: api-2
    build:  .
    command: node api.js
    ports: 
      - "8082:8080"
    volumes:
      - .:/api

