version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    depends_on:
        - nodejs-api
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
  nodejs-api:
    container_name: nodejs-api
    build:  .
    command: node api.js
    ports: 
      - "8080:8080"
    volumes:
      - .:/api
